# Dependabot can fix vulnerable dependencies by raising pull requests with security updates.
# Configuration options:
#   https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
