# Configures the Prettier tool with settings not available in the .editorconfig file.
# More info: https://prettier.io/docs/en/configuration.html

# Specify the line length that the printer will wrap on.
# Overrides max_line_length from the .editorconfig file.
# More info: https://prettier.io/docs/en/options.html#print-width
printWidth: 100

# Prefer to use double quotes.
# More info: https://prettier.io/docs/en/options.html#quotes
singleQuote: false

# Only add quotes around object parameters when required.
# More info: https://prettier.io/docs/en/options.html#quote-props
quoteProps: "as-needed"

# Wrap markdown prose if it exceeds the print width.
# More info: https://prettier.io/docs/en/options.html#prose-wrap
proseWrap: "always"

# Allow formatting quoted code embedded in the file.
# More info: https://prettier.io/docs/en/options.html#embedded-language-formatting
embeddedLanguageFormatting: "auto"
